spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/daxblog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: daxblog
    password: AA5NR5dmTiCYxED2
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

langchain4j:
  openai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      model-name: deepseek-chat
      temperature: 0.0
      top-p: 0.1

server:
  port: 8713

api:
  weather:
    base-url: "https://v2.xxapi.cn/api/weather"
    key: "7a0da87f193a74e9"
  oil:
    base-url: "https://v2.xxapi.cn/api/oilPrice"
